### ISSUE TITLE
[Suggestion] Add SQLite support

### ISSUE THREAD

**Issue by Drc-DEV** [slipcor/PVPStats#13]
Add support for sqlite for servers that can't set up a mysql server

**Comment by slipcor** [comment]
okay :P I will work on this this week ^^

**Comment by slipcor** [comment]
good luck! I am catching but displaying all the errors but it SHOULD work, I did the testing I could, with a second minecraft account that I have, but it is not the same as literally have people kill each other :D

https://www.spigotmc.org/resources/pvp-stats.59124/
