### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by zasnaz** [slipcor/PVPStats#25]
Hey,
Is there any possibility to add new column (assists) in the next version?
Thank you.

**Comment by slipcor** [comment]
The next version, if I ever get it to work with a reporter, is a move to UUIDs because there are serious issues when a player gets renamed --- apparently.

After that, I will think about it ^^

So assists are basically "damage done to a player that did not lead to a kill", right?

**Comment by zasnaz** [comment]
Yea right 
Thank you.

**Comment by slipcor** [comment]
Hey I have not heard back from the person who wanted an update about the UUIDs - could you maybe test this build? (maybe backup your database in case something breaks?)

http://pa.slipcor.net/pvpstats.jar

This should work as intended, "only" the internal checking has been moved to UUIDs, all entries are created the same way, so the database will be backwards compatible in case thi sbuild throws errors. I have tested this on a test server but I have no players to test, so testing PVP is really hard for me :/

**Comment by zasnaz** [comment]
Sorry for being late, can I test this now or you have test it already ?

**Comment by slipcor** [comment]
Hey :)

I have still not received any tester updates, so it would be greatly appreciated if you could give it a go :)
