### ISSUE TITLE
/pvpstats set ... not working and also freeze the game

### ISSUE THREAD

**Issue by emanondev** [slipcor/PVPStats#26]
using 
/pvpstats set [player] [type] [amount]

freeze the game i suppose 
DatabaseAPI.setSpecificStat();
should be called async

also the changes aren't applied:
/pvpstats show, give the same result before and after /pvpstats set

https://pastebin.com/j6xtWhfk

**Comment by slipcor** [comment]
Even though I do not really think calling it async will fix the problem, I will look into what could be going on. I sadly have no SQL database so if it is specific to that, not sure what I can do.

I will look at this tomorrow!

**Comment by slipcor** [comment]
I have done as you said. I will release this version. I have waited for testers to report back if the current version is stable. I will take their silence as a positive result. If it causes issues, I can tell people to downgrade again. I can not feasibly test this build so... sorry if it breaks

**Comment by emanondev** [comment]
i'm sorry i created a plugin to replace pvpstats i can't test it on my server anymore, if no one reports any errors i think this issue may be closed
