### ISSUE TITLE
Placeholder api

### ISSUE THREAD

**Issue by Zapry** [slipcor/PVPStats#49]
Hello, I want to report (suggest) the posibility to change placeholders format. 
![image](https://github.com/slipcor/PVPStats/assets/131723442/5b42912d-f567-44c2-ab0f-6d40656b85d5)

This is the placeholder view and i want to make something more like this

![image](https://github.com/slipcor/PVPStats/assets/131723442/fb06ea9f-6549-4883-a9b5-db956c2e2424)

**Comment by slipcor** [comment]
2 things to update in your "lang.yml":

1) set statistic-format-number to `%0% <#aaaaaa>. %1%` where aaaaaa is the hex color for the yellow number you want
2) set statistic-format-value to `"<#aaaaaa>%0% <#bbbbbb>- <#cccccc>%1%` where aaaaaa is the red you want for the player name color, where bbbbbb is the color of the hyphen and cccccc the hex color of the number value
