### ISSUE TITLE
MySQL Errors

### ISSUE THREAD

**Issue by MeMyselfMC** [slipcor/PVPStats#5]
Ever since we installed this plugin on our server, which would be about 18 hours ago, we've been getting the following errors. For most players it says they don't exist when you /pvpstats them, and kills reset on death along with the killstreak, but deaths don't.

Errors:
- http://hastebin.com/owehaqimah.vbs - This one is printed in console during the start-up process.
- http://hastebin.com/aceqazexal.vbs - This one is printed in console as players login, logout, die, or kill other players.

At first when I checked the database there were no pvpstats tables created at all, but after reloading the plugin with /pvpstats reload a couple of times, the 'pvpstats' table was created, but contained data for a few players only. The second error kept coming up.

Using Spigot 1.8.8 (3 builds behind the current one, Java 8) and MySQL 5.5.37.

config.yml: http://hastebin.com/ivivirikip.sm
pvpstats v0.8.16 from dev.bukkit.org

**Comment by slipcor** [comment]
can you test this build? I think I messed up the default value (that's what it sais) - this causes all your issues :(

http://pa.slipcor.net/pvpstats.jar

if this works (it should) I can push it to bukkit :D

**Comment by MeMyselfMC** [comment]
Thanks, that works ^.^
However, I've been noticing that it kind of lags when you kill someone. Here's my timings:
http://timings.aikar.co/?url=14278176

**Comment by slipcor** [comment]
check the latest download:
http://dev.bukkit.org/bukkit-plugins/pvp-stats/files/
I added a purge command, I am quite sure it's outdated player entries clogging up the database.

It removes entries older than X days, so people need to stay active :)
