### ISSUE TITLE
[Feature Request] Please make possibility to separate leaderboard papi nickname and vaule

### ISSUE THREAD

**Issue by roggy666** [slipcor/PVPStats#50]
Example:
%slipcorpvpstats_top_kills_nick_1%
%slipcorpvpstats_top_kills_value_1%

**Comment by slipcor** [comment]
Implemented here

https://github.com/slipcor/PVPStats/blob/master/src/main/java/net/slipcor/pvpstats/classes/PlaceholderAPIHook.java#L89

Not documented :)

So in your case:

%slipcorpvpstats_top_kills_1_name%
%slipcorpvpstats_top_kills_1_value%

I will update the documentation right now
