### ISSUE TITLE
NPE: calcResult

### ISSUE THREAD

**Issue by ChrisLane** [slipcor/PVPStats#8]
#### Versions
PVPStats v0.8.30
Running Thermos build 58 (https://github.com/CyberdyneCC/Thermos/releases/tag/58)

#### Logs
Server starts up correctly, plugin successfully stores kills in the "pvpstats" table, "pvpkillstats" is empty.

Upon running /pvpstats [player] this error occurs: http://paste2.org/wdemxU6v

**Comment by slipcor** [comment]
Can you check your ELO definition? It seems the elo definition is null for some reason, and that causes the error you see. What does your config look like?

Either that or your server does not support JavaScript maybe?

**Comment by slipcor** [comment]
https://github.com/slipcor/PVPStats/blob/master/src/main/java/net/slipcor/pvpstats/PSMySQL.java#L303

**Comment by ChrisLane** [comment]
The config is default with mysql settings added. I'm checking into it a bit atm.

**Comment by ChrisLane** [comment]
Fixed it by changing the script engine to nashorn.

**Comment by slipcor** [comment]
ok so I do not need to fix anything on my end? :)

**Comment by ChrisLane** [comment]
Well you're compiling for Java 7 so if we assume everyone's on that version then that's fine but otherwise it might be a good idea to look into an alternative, especially since Java 8 is recommended.

What version are you running with?

On 19/12/16 17:05, slipcor wrote:

ok so I do not need to fix anything on my end? :)
